---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  http_proxy: http://proxy.sg.fap:3128
  https_proxy: http://proxy.sg.fap:3128
  no_proxy: localhost,127.0.0.1

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[httpd_ssl_proxy::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
