---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
    driver_config:
      image: centos:6.6
      platform: centos

suites:
  - name: ubuntu12
    excludes:
      - centos-6.6
      - ubuntu-14.04
    run_list:
      - recipe[spacewalk-client::ubuntu]
    attributes:
      spacewalk:
        reg:
          key: "1-ubuntu12.04-key"
          server: "http://spacewalk.hc.lan"
        enable_rhncfg: true
        rhncfg:
          actions:
            run: true    
  - name: ubuntu14
    excludes:
      - centos-6.6
      - ubuntu-12.04
    run_list:
      - recipe[spacewalk-client::ubuntu]
    attributes:
      spacewalk:
        reg:
          key: "1-ubuntu14.04-key"
          server: "http://spacewalk.hc.lan"
        enable_rhncfg: true
        rhncfg:
          actions:
            run: true        
  - name: centos
    excludes:
      - ubuntu-12.04
      - ubuntu-14.04
    run_list:
      - recipe[spacewalk-client::rhel]
    attributes:
      spacewalk:
        reg:
          key: "1-centos6"
          server: "http://spacewalk.hc.lan"
        enable_rhncfg: true
        rhncfg:
          actions:
            run: true     
